apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hiteen-mongo-pvc
  namespace: hiteen
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: hiteen-mongo
  namespace: hiteen
spec:
#  type: ClusterIP
  type: NodePort
  ports:
    - port: 27017
      targetPort: 27017
      name: mongodb
  selector:
    app: hiteen-mongo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hiteen-mongo
  namespace: hiteen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hiteen-mongo
  template:
    metadata:
      labels:
        app: hiteen-mongo
    spec:
      containers:
        - name: mongo
          image: mongo:7
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_DATABASE
              value: "hiteen"
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "hiteen"
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "1234"
          volumeMounts:
            - name: mongo-storage
              mountPath: /data/db
      volumes:
        - name: mongo-storage
          persistentVolumeClaim:
            claimName: hiteen-mongo-pvc
