apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgres-backup
  namespace: {{ .Values.namespace }}
spec:
  schedule: "0 3 * * *"  # 매일 새벽 3시 백업
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          nodeSelector:
            node-type: private
          containers:
            - name: db-backup
              image: postgres:16
              env:
                - name: PGPASSWORD
                  value: "hiteen@2025"
              command:
                - /bin/bash
                - -c
                - |
                  TIMESTAMP=$(date +'%Y%m%d-%H%M%S')
                  pg_dump -h 10.8.0.200 -U hiteen -d hiteen2-dev -F c -f /backup/hiteen-${TIMESTAMP}.dump
                  echo "✅ Backup completed at ${TIMESTAMP}"
              volumeMounts:
                - name: nfs-backup
                  mountPath: /backup
          volumes:
            - name: nfs-backup
              persistentVolumeClaim:
                claimName: nfs-pvc-backup
