apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-images
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.nfs.storage }}
  volumeName: nfs-pv-images