apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-backup
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.backupNfs.storage }}
  volumeName: nfs-pv-backup
  storageClassName: ""
