# ==============================
# Redis ConfigMap
# ==============================
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: {{ .Values.namespace }}
data:
  redis.conf: |
    port 6379
    bind 0.0.0.0
    cluster-enabled yes
    cluster-config-file nodes.conf
    cluster-node-timeout 5000
    appendonly yes
    dir /data
    protected-mode no
    requirepass {{ .Values.redis.password }}
    masterauth {{ .Values.redis.password }}

---
# ==============================
# Redis Headless Service
# ==============================
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: {{ .Values.namespace }}
spec:
  clusterIP: None
  ports:
    - name: redis
      port: {{ .Values.redis.service.port | default 6379 }}
    - name: cluster-bus
      port: {{ .Values.redis.service.clusterPort | default 16379 }}
  selector:
    app: redis

---
# ==============================
# Redis StatefulSet
# ==============================
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: {{ .Values.namespace }}
spec:
  serviceName: "redis"
  replicas: {{ .Values.redis.replicas }}
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      containers:
        - name: redis
          image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
          imagePullPolicy: {{ .Values.redis.image.pullPolicy | default "IfNotPresent" }}
          command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
          ports:
            - containerPort: {{ .Values.redis.service.port | default 6379 }}
            - containerPort: {{ .Values.redis.service.clusterPort | default 16379 }}
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: redis-password
          resources:
            {{- toYaml .Values.redis.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /usr/local/etc/redis
            - name: redis-data
              mountPath: /data
      volumes:
        - name: config
          configMap:
            name: redis-config
  volumeClaimTemplates:
    - metadata:
        name: redis-data
      spec:
        accessModes: {{ toYaml .Values.redis.accessModes | nindent 8 }}
        resources:
          requests:
            storage: {{ .Values.redis.storageSize | default "2Gi" }}
        storageClassName: {{ .Values.redis.storageClass }}

---
# ==============================
# Redis Cluster Initialization Job (Helm Hook)
# ==============================
  {{- if .Values.redis.clusterInit.enabled }}
  {{- $replicas := int .Values.redis.replicas }}
apiVersion: batch/v1
kind: Job
metadata:
  name: redis-cluster-create
  namespace: {{ .Values.namespace }}
  annotations:
    "helm.sh/hook": post-upgrade
    "helm.sh/hook-weight": "80"
    "helm.sh/hook-wait": "true"
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      serviceAccountName: default
      containers:
        - name: redis-cluster-create
          image: redis:7.2
          command:
            - "bash"
            - "-c"
            - |
              set -eu
              echo "📦 Installing redis-tools..."
              apt-get update -qq && apt-get install -y -qq redis-tools kubectl > /dev/null

              PING_INTERVAL={{ $.Values.redis.clusterInit.pingInterval | default 3 }}
              WAIT_TIMEOUT={{ $.Values.redis.clusterInit.waitTimeout | default 300 }}
              REPLICAS={{ $replicas }}
              PASSWORD="{{ .Values.redis.password }}"
              NAMESPACE="{{ $.Values.namespace }}"

              echo "🕓 Waiting for Redis StatefulSet to exist..."
              for i in $(seq 1 30); do
                if kubectl get statefulset redis -n "$NAMESPACE" >/dev/null 2>&1; then
                  echo "✅ Redis StatefulSet found!"
                  break
                fi
                echo "Redis StatefulSet not found yet... waiting 5s."
                sleep 5
              done

              echo "🕓 Waiting for Redis pods to be ready..."
              for i in $(seq 0 $((REPLICAS - 1))); do
                COUNT=0
                while true; do
                  if redis-cli -a "$PASSWORD" -h redis-$i.redis.$NAMESPACE.svc.cluster.local ping 2>/dev/null | grep -q PONG; then
                    echo "✅ Pod redis-$i is ready"
                    break
                  fi
                  COUNT=$((COUNT + PING_INTERVAL))
                  if (( COUNT > WAIT_TIMEOUT )); then
                    echo "⛔ Pod redis-$i not ready after $WAIT_TIMEOUT seconds."
                    exit 1
                  fi
                  echo "Pod redis-$i not ready yet... waiting $PING_INTERVAL sec"
                  sleep $PING_INTERVAL
                done
              done

              echo "🔍 Checking cluster state..."
              if redis-cli -a "$PASSWORD" -h redis-0.redis.$NAMESPACE.svc.cluster.local cluster info | grep -q "cluster_state:ok"; then
                echo "🔵 Redis cluster already initialized. Skipping creation."
                exit 0
              fi

              echo "⚡ Creating Redis cluster..."
              yes yes | redis-cli -a "$PASSWORD" --cluster create \
                $(for i in $(seq 0 $((REPLICAS - 1))); do echo -n "redis-$i.redis.$NAMESPACE.svc.cluster.local:6379 "; done) \
                --cluster-replicas {{ .Values.redis.clusterReplicas }}

              echo "✅ Redis cluster successfully created."
  {{- end }}
