apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: {{ .Values.namespace }}
spec:
  serviceName: "redis"
  replicas: {{ .Values.redis.replicas }}
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      containers:
        - name: redis
          image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
          imagePullPolicy: {{ .Values.redis.image.pullPolicy | default "IfNotPresent" }}
          command: [ "sh", "-c", "redis-server /usr/local/etc/redis/redis.conf --protected-mode no" ]
          ports:
            - containerPort: {{ .Values.redis.service.port | default 6379 }}
            - containerPort: {{ .Values.redis.service.clusterPort | default 16379 }}
          resources: {{- toYaml .Values.redis.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /usr/local/etc/redis
            - name: redis-data
              mountPath: /data
      volumes:
        - name: config
          configMap:
            name: redis-config

  volumeClaimTemplates:
    - metadata:
        name: redis-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: {{ .Values.redis.storageClass | quote }}
        resources:
          requests:
            storage: {{ .Values.redis.storage | default "1Gi" }}
