# ==============================
# Redis ConfigMap
# ==============================
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: {{ .Values.namespace }}
data:
  redis.conf: |
    port 6379
    bind 0.0.0.0
    cluster-enabled yes
    cluster-config-file nodes.conf
    cluster-node-timeout 5000
    appendonly yes
    dir /data
    protected-mode no
    requirepass {{ .Values.redis.password }}
    masterauth {{ .Values.redis.password }}

---
# ==============================
# Redis Headless Service
# ==============================
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: {{ .Values.namespace }}
spec:
  clusterIP: None
  ports:
    - name: redis
      port: {{ .Values.redis.service.port | default 6379 }}
    - name: cluster-bus
      port: {{ .Values.redis.service.clusterPort | default 16379 }}
  selector:
    app: redis

---
# ==============================
  # Redis Cluster Initialization Job
  # ==============================
  {{- if .Values.redis.clusterInit.enabled }}
  {{- $replicas := int .Values.redis.replicas }}
apiVersion: batch/v1
kind: Job
metadata:
  name: redis-cluster-create
  namespace: {{ .Values.redis.clusterInit.namespace }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: redis-cluster-create
          image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
          command:
            - "bash"
            - "-c"
            - |
              echo "🕓 Waiting for Redis pods to be ready..."
              for i in $(seq 0 {{ sub $replicas 1 }}); do
                until redis-cli -a {{ .Values.redis.password }} -h redis-$i.redis.{{ $.Values.namespace }}.svc.cluster.local ping | grep -q PONG; do
                  echo "Pod redis-$i not ready yet..."
                  sleep {{ $.Values.redis.clusterInit.pingInterval | default 3 }}
                done
              done

              echo "✅ All Redis pods are ready. Creating cluster..."
              redis-cli -a {{ .Values.redis.password }} --cluster create \
                {{- range $i, $e := until $replicas }}
                redis-{{ $i }}.redis.{{ $.Values.namespace }}.svc.cluster.local:6379 \
                {{- end }}
                --cluster-replicas {{ .Values.redis.clusterReplicas }} --cluster-yes
  {{- end }}