apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.soketi.name }}-svc
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.soketi.name }}
spec:
  type: {{ .Values.soketi.service.type | default "ClusterIP" }}
  selector:
    app: {{ .Values.soketi.name }}
  ports:
    - name: http
      port: {{ .Values.soketi.service.port | default 6001 }}
      targetPort: {{ .Values.soketi.service.port | default 6001 }}
      protocol: TCP

