apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.app.name }}
spec:
  type: {{ default "ClusterIP" .Values.app.service.type }}
  selector:
    app: {{ .Values.app.name }}
  ports:
    - name: http
      port: {{ .Values.app.service.port }}
      targetPort: {{ .Values.app.service.port }}
      protocol: TCP

