package kr.jiasoft.hiteen.feature.giftishow.dto.goods

data class GoodsDto(
    val goodsNo: Int,
    val goodsCode: String,
    val goodsName: String?,
    val brandCode: String?,
    val brandName: String?,
    val content: String?,
    val contentAddDesc: String?,
    val srchKeyword: String?,
    val mdCode: String?,
    val category1Seq: Int?,
    val goodsTypeNm: String?,
    val goodsTypeDtlNm: String?,
    val goodsImgS: String?,
    val goodsImgB: String?,
    val brandIconImg: String?,
    val goodsDescImgWeb: String?,      // 상세 이미지
    val mmsGoodsImg: String?,
    val salePrice: Int?,
    val realPrice: Int?,
    val discountRate: Double?,
    val discountPrice: Int?,
    val goodsStateCd: String?,
    val endDate: String?,
    val affiliate: String?,
    val affiliateId: String?,
    val limitDay: Int?,
    val goodsComId: String?,
    val goodsComName: String?,
    val exhGenderCd: String?,
    val exhAgeCd: String?,
    val validPrdDay: String?,
    val validPrdTypeCd: String = "01",
    val mmsReserveFlag: String?,
    val mmsBarcdCreateYn: String?,
    val rmCntFlag: String?,
    val rmIdBuyCntFlagCd: String?,
    val saleDateFlagCd: String?,
    val saleDateFlag: String?,
    val popular: Int?
)