{{- if and .Values.nfs.enabled .Values.nfs.createPV }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-images
spec:
  capacity:
    storage: {{ .Values.nfs.storage }}
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: {{ .Values.nfs.path }}
    server: {{ .Values.nfs.server }}
{{- end }}

