{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: hiteen-app-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  # Database
  db-host: {{ .Values.secrets.db.host | default "10.8.0.200" | quote }}
  db-name: {{ .Values.secrets.db.name | default "hiteen" | quote }}
  db-user: {{ .Values.secrets.db.user | default "hiteen" | quote }}
  db-password: {{ .Values.secrets.db.password | quote }}

  # MongoDB
  mongo-host: {{ .Values.secrets.mongo.host | default "10.8.0.200" | quote }}
  mongo-user: {{ .Values.secrets.mongo.user | default "hiteen" | quote }}
  mongo-password: {{ .Values.secrets.mongo.password | quote }}
  mongo-db: {{ .Values.secrets.mongo.db | default "hiteen" | quote }}

  # JWT
  jwt-secret: {{ .Values.secrets.jwt.secret | quote }}

  # SMS (Optional)
  {{- if .Values.secrets.sms }}
  sms-api-key: {{ .Values.secrets.sms.apiKey | default "" | quote }}
  kakao-sender-key: {{ .Values.secrets.sms.kakaoSenderKey | default "" | quote }}
  {{- end }}

  # Giftishow (Optional)
  {{- if .Values.secrets.giftishow }}
  giftishow-auth-key: {{ .Values.secrets.giftishow.authKey | default "" | quote }}
  giftishow-token-key: {{ .Values.secrets.giftishow.tokenKey | default "" | quote }}
  {{- end }}

  # External APIs (Optional)
  {{- if .Values.secrets.external }}
  neis-api-key: {{ .Values.secrets.external.neisApiKey | default "" | quote }}
  kakao-api-key: {{ .Values.secrets.external.kakaoApiKey | default "" | quote }}
  {{- end }}
{{- end }}

